<a href="https://colab.research.google.com/github/gayatriverm/mlproject/blob/main/Logistic_Regression_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

In [ ]:
import numpy as np
import pandas as pd

Training Data

Loading data

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/train.csv")
data.shape

(668, 11)

In [ ]:
data

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.0000,NaN,S,1
1,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.0500,NaN,S,0
2,2,"Morley, Mr. Henry Samuel (""Mr Henry Marshall"")",male,39.0,0,0,250655,26.0000,NaN,S,0
3,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.0750,NaN,S,0
4,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
663,2,"Ilett, Miss. Bertha",female,17.0,0,0,SO/C 14885,10.5000,NaN,S,1
664,3,"Morrow, Mr. Thomas Rowan",male,NaN,0,0,372622,7.7500,NaN,Q,0
665,3,"Bing, Mr. Lee",male,32.0,0,0,1601,56.4958,NaN,S,1
666,3,"Strandberg, Miss. Ida Sofia",female,22.0,0,0,7553,9.8375,NaN,S,0
667,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000,NaN,Q,1

Cleaning data

In [ ]:
data=data.drop(["Name","Cabin","Ticket"], axis=1)
data

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived
0         2  female  29.0      1      0  26.0000        S         1
1         3    male   NaN      0      0   8.0500        S         0
2         2    male  39.0      0      0  26.0000        S         0
3         3  female  29.0      0      4  21.0750        S         0
4         3    male  25.0      0      0   7.0500        S         0
..      ...     ...   ...    ...    ...      ...      ...       ...
663       2  female  17.0      0      0  10.5000        S         1
664       3    male   NaN      0      0   7.7500        Q         0
665       3    male  32.0      0      0  56.4958        S         1
666       3  female  22.0      0      0   9.8375        S         0
667       3  female   NaN      1      0  15.5000        Q         1

[668 rows x 8 columns]

Data preperation

In [ ]:
genders = {"male": 0, "female": 1}
data1 = [data]

for dataset in data1:
    dataset['Sex'] = dataset['Sex'].map(genders)

In [ ]:
data

     Pclass  Sex   Age  SibSp  Parch     Fare Embarked  Survived
0         2    1  29.0      1      0  26.0000        S         1
1         3    0   NaN      0      0   8.0500        S         0
2         2    0  39.0      0      0  26.0000        S         0
3         3    1  29.0      0      4  21.0750        S         0
4         3    0  25.0      0      0   7.0500        S         0
..      ...  ...   ...    ...    ...      ...      ...       ...
663       2    1  17.0      0      0  10.5000        S         1
664       3    0   NaN      0      0   7.7500        Q         0
665       3    0  32.0      0      0  56.4958        S         1
666       3    1  22.0      0      0   9.8375        S         0
667       3    1   NaN      1      0  15.5000        Q         1

[668 rows x 8 columns]

In [ ]:
embarked = {"S": 0, "Q": 1, "C": 2}
data11 = [data]

for dataset in data11:
    dataset['Embarked'] = dataset['Embarked'].map(embarked)

In [ ]:
data

     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0         2    1  29.0      1      0  26.0000       0.0         1
1         3    0   NaN      0      0   8.0500       0.0         0
2         2    0  39.0      0      0  26.0000       0.0         0
3         3    1  29.0      0      4  21.0750       0.0         0
4         3    0  25.0      0      0   7.0500       0.0         0
..      ...  ...   ...    ...    ...      ...       ...       ...
663       2    1  17.0      0      0  10.5000       0.0         1
664       3    0   NaN      0      0   7.7500       1.0         0
665       3    0  32.0      0      0  56.4958       0.0         1
666       3    1  22.0      0      0   9.8375       0.0         0
667       3    1   NaN      1      0  15.5000       1.0         1

[668 rows x 8 columns]

In [ ]:
mean = data["Age"].mean()
std = data["Age"].std()
data.Age.fillna(mean,inplace=True)
data.Embarked.fillna(0,inplace=True)

In [ ]:
d = data.isnull().sum()
print(d)
data=data.values
data.shape

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

(668, 8)

In [ ]:
x1= data[:,:-1]
y1= data[:,-1]
print(x1.shape,y1.shape)

(668, 7) (668,)

Testing Data

In [ ]:
data1=pd.read_csv("/content/drive/MyDrive/test.csv")
data1=data1.drop(["Name","Cabin","Ticket"],axis=1)
genders={"male":0,"female":1}
data2=[data1]
for dataset in data2:
  dataset["Sex"]=dataset["Sex"].map(genders)
embarked={'S':0,'Q':1,'C':2}
data22=[data1]
for dataset in data22:
  dataset["Embarked"]=dataset["Embarked"].map(embarked)
mean = data1["Age"].mean()
std = data1["Age"].std()
data1.Age.fillna(mean,inplace=True)
data1.Embarked.fillna(0,inplace=True)
d=data1.isnull().sum()
print(d)
#data1.head(8)
data1=data1.values
data1.shape

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

(223, 7)

In [ ]:
x1.shape,data1.shape

((668, 7), (223, 7))

In [ ]:
from sklearn import preprocessing as pp

In [ ]:
scaler=pp.StandardScaler()
scaler.fit(x1)
x1=scaler.transform(x1)
data1=scaler.transform(data1)
print(data1)

[[-3.56680918e-01 -7.51267469e-01 -1.70280321e+00 ...  6.94117561e-01
   1.03461451e-01 -5.87892987e-01]
 [-1.56002866e+00  1.33108386e+00  1.51439177e+00 ... -4.76767618e-01
  -1.35477405e-01 -5.87892987e-01]
 [ 8.46666826e-01 -7.51267469e-01 -4.53892900e-04 ... -4.76767618e-01
  -5.37176352e-01  6.54868137e-01]
 ...
 [-1.56002866e+00  1.33108386e+00 -9.96589681e-01 ... -4.76767618e-01
   1.69663741e+00  1.89762926e+00]
 [ 8.46666826e-01 -7.51267469e-01  1.04358275e+00 ... -4.76767618e-01
  -5.65606207e-01 -5.87892987e-01]
 [-3.56680918e-01 -7.51267469e-01  5.33539639e-01 ...  1.86500274e+00
  -1.33914039e-01 -5.87892987e-01]]

In [ ]:
df=pd.DataFrame(x1)
df["c"]= 1
x2=df.values
df1=pd.DataFrame(data1)
df1["c"]= 1
x3=df1.values

In [ ]:
def step_gradient(points,learning_rate,m):
    m_slope=np.zeros(8)
    M=len(points)
    for i in range(M):
        x=points[i,:]
        y=y1[i]
        for j in range(len(x)):
            s=[]
            for k in range(len(x)):
                s.append(x[k]*m[k])
            h=1/(1+ math.exp(-1*sum(s)))
            m_slope[j]+=(-1/M)*(y-h)*x[j]

    new_m=m-learning_rate*m_slope

    return new_m

In [ ]:
def gd(points,learning_rate,num_iterations):
    m=np.zeros(8)
    for i in range(num_iterations):
        m=step_gradient(points,learning_rate,m)
        print(i,"Cost:",cost(points,m))
    return m

In [ ]:
def cost(points,m):
    total_cost=0
    M=len(points)
    for i in range(M):
        x=points[i,:]
        y=y1[i]
        b=[]
        for j in range(len(m)):
            b.append (m[j]*x[j])
        h =1/(1+math.exp(-1*sum(b)))
        total_cost+=(-1/M)*(y*(math.log(h))+((1-y)*(math.log(1-h))))
    return total_cost

In [ ]:
def predicted(x3,m):
    y_p=[]
    for i in range(len(x3)):
        b=[]
        x=x3[i,:]
        for j in range(len(m)):
            b.append(m[j]*x[j])
        h=1/(1+math.exp(-1*sum(b)))
        if h>0.5:
            y_p.append(1)
        elif h<=0.5:
            y_p.append(0)
    return(y_p)

In [ ]:
def run():
    learning_rate=0.1
    num_iterations=500
    m =gd(x2, learning_rate,num_iterations)
    slope=m
    y_predicted=predicted(x3,slope)
    print(m)
    print(y_predicted)
    print(len(y_predicted))
    np.savetxt("y_titanic.csv",y_predicted,fmt='%.5f')

In [ ]:
run()

0 Cost: 0.6805943185748515
1 Cost: 0.6689360039802368
2 Cost: 0.6580994209006361
3 Cost: 0.6480169902206406
4 Cost: 0.6386263585650872
5 Cost: 0.6298702580581061
6 Cost: 0.6216962767659292
7 Cost: 0.6140565726585351
8 Cost: 0.6069075567092109
9 Cost: 0.6002095641991478
10 Cost: 0.5939265277758915
11 Cost: 0.5880256614111345
12 Cost: 0.5824771610355471
13 Cost: 0.5772539251434331
14 Cost: 0.5723312968870009
15 Cost: 0.5676868279580221
16 Cost: 0.5633000637457072
17 Cost: 0.5591523487524863
18 Cost: 0.5552266509569499
19 Cost: 0.5515074036703498
20 Cost: 0.547980363391138
21 Cost: 0.544632482186255
22 Cost: 0.5414517931932619
23 Cost: 0.5384273079266465
24 Cost: 0.5355489241728136
25 Cost: 0.5328073433633843
26 Cost: 0.5301939964204274
27 Cost: 0.5277009771667116
28 Cost: 0.5253209824874316
29 Cost: 0.5230472585158652
30 Cost: 0.5208735521939919
31 Cost: 0.518794067630158
32 Cost: 0.5168034267397841
33 Cost: 0.5148966337122768
34 Cost: 0.5130690428983503
35 Cost: 0.5113163297572854
36 Cost: 0.5096344645439428
37 Cost: 0.5080196884510265
38 Cost: 0.5064684919537248
39 Cost: 0.5049775951317922
40 Cost: 0.5035439297689173
41 Cost: 0.5021646230511203
42 Cost: 0.5008369827052632
43 Cost: 0.4995584834359532
44 Cost: 0.4983267545342649
45 Cost: 0.4971395685451822
46 Cost: 0.4959948308925692
47 Cost: 0.4948905703710831
48 Cost: 0.4938249304238074
49 Cost: 0.492796161132742
50 Cost: 0.4918026118567189
51 Cost: 0.49084272445789423
52 Cost: 0.4899150270638797
53 Cost: 0.4890181283177968
54 Cost: 0.48815071207324745
55 Cost: 0.48731153249537135
56 Cost: 0.48649940953288606
57 Cost: 0.48571322472938816
58 Cost: 0.4849519173451793
59 Cost: 0.4842144807635697
60 Cost: 0.4834999591580369
61 Cost: 0.4828074443988079
62 Cost: 0.4821360731793455
63 Cost: 0.4814850243450308
64 Cost: 0.4808535164078822
65 Cost: 0.48024080523259816
66 Cost: 0.47964618188051733
67 Cost: 0.4790689705992214
68 Cost: 0.4785085269466089
69 Cost: 0.477964236039187
70 Cost: 0.4774355109152223
71 Cost: 0.47692179100415927
72 Cost: 0.4764225406944476
73 Cost: 0.4759372479925562
74 Cost: 0.4754654232665434
75 Cost: 0.47500659806809925
76 Cost: 0.4745603240274601
77 Cost: 0.4741261718160269
78 Cost: 0.4737037301719698
79 Cost: 0.47329260498441145
80 Cost: 0.4728924184321809
81 Cost: 0.47250280817339846
82 Cost: 0.4721234265824614
83 Cost: 0.4717539400312446
84 Cost: 0.4713940282115893
85 Cost: 0.4710433834963412
86 Cost: 0.47070171033643354
87 Cost: 0.47036872469167934
88 Cost: 0.4700441534930945
89 Cost: 0.4697277341347678
90 Cost: 0.4694192139933803
91 Cost: 0.46911834997367996
92 Cost: 0.46882490807826666
93 Cost: 0.4685386630002071
94 Cost: 0.4682593977370916
95 Cost: 0.4679869032252171
96 Cost: 0.4677209779926949
97 Cost: 0.4674614278303686
98 Cost: 0.46720806547946436
99 Cost: 0.4669607103350182
100 Cost: 0.4667191881641422
101 Cost: 0.4664833308382886
102 Cost: 0.4662529760787015
103 Cost: 0.4660279672143161
104 Cost: 0.4658081529513912
105 Cost: 0.46559338715423415
106 Cost: 0.4653835286363945
107 Cost: 0.46517844096174854
108 Cost: 0.46497799225494413
109 Cost: 0.4647820550206888
110 Cost: 0.46459050597140916
111 Cost: 0.46440322586283495
112 Cost: 0.4642200993370935
113 Cost: 0.4640410147729075
114 Cost: 0.46386586414253694
115 Cost: 0.46369454287510864
116 Cost: 0.46352694972600733
117 Cost: 0.4633629866520215
118 Cost: 0.4632025586919492
119 Cost: 0.4630455738523876
120 Cost: 0.46289194299845227
121 Cost: 0.46274157974917535
122 Cost: 0.46259440037735794
123 Cost: 0.46245032371365924
124 Cost: 0.4623092710547089
125 Cost: 0.46217116607504893
126 Cost: 0.4620359347427472
127 Cost: 0.46190350523845614
128 Cost: 0.4617738078778083
129 Cost: 0.4616467750369586
130 Cost: 0.46152234108113843
131 Cost: 0.4614004422960752
132 Cost: 0.46128101682215666
133 Cost: 0.4611640045912003
134 Cost: 0.46104934726572366
135 Cost: 0.4609369881805888
136 Cost: 0.4608268722869287
137 Cost: 0.46071894609823955
138 Cost: 0.46061315763854976
139 Cost: 0.4605094563925833
140 Cost: 0.46040779325781067
141 Cost: 0.46030812049831554
142 Cost: 0.4602103917004108
143 Cost: 0.4601145617299001
144 Cost: 0.4600205866909422
145 Cost: 0.45992842388643645
146 Cost: 0.4598380317798674
147 Cost: 0.4597493699585415
148 Cost: 0.4596623990981753
149 Cost: 0.45957708092875704
150 Cost: 0.45949337820164304
151 Cost: 0.45941125465783766
152 Cost: 0.45933067499740005
153 Cost: 0.4592516048499401
154 Cost: 0.4591740107461564
155 Cost: 0.459097860090376
156 Cost: 0.4590231211340485
157 Cost: 0.4589497629501741
158 Cost: 0.4588777554086053
159 Cost: 0.4588070691522094
160 Cost: 0.4587376755738396
161 Cost: 0.45866954679409994
162 Cost: 0.45860265563986297
163 Cost: 0.4585369756235124
164 Cost: 0.45847248092288434
165 Cost: 0.4584091463618825
166 Cost: 0.45834694739173953
167 Cost: 0.4582858600729004
168 Cost: 0.45822586105749796
169 Cost: 0.45816692757241706
170 Cost: 0.45810903740290243
171 Cost: 0.4580521688767059
172 Cost: 0.4579963008487473
173 Cost: 0.4579414126862721
174 Cost: 0.45788748425448217
175 Cost: 0.45783449590263225
176 Cost: 0.4577824284505689
177 Cost: 0.45773126317569035
178 Cost: 0.45768098180032907
179 Cost: 0.4576315664795225
180 Cost: 0.45758299978917505
181 Cost: 0.4575352647145827
182 Cost: 0.4574883446393175
183 Cost: 0.45744222333445905
184 Cost: 0.4573968849481534
185 Cost: 0.45735231399549237
186 Cost: 0.4573084953487128
187 Cost: 0.45726541422767636
188 Cost: 0.4572230561906544
189 Cost: 0.45718140712538374
190 Cost: 0.4571404532403933
191 Cost: 0.45710018105659245
192 Cost: 0.45706057739910433
193 Cost: 0.4570216293893498
194 Cost: 0.4569833244373674
195 Cost: 0.4569456502343456
196 Cost: 0.45690859474539514
197 Cost: 0.4568721462025155
198 Cost: 0.4568362930977788
199 Cost: 0.4568010241767044
200 Cost: 0.4567663284318294
201 Cost: 0.45673219509646207
202 Cost: 0.45669861363861985
203 Cost: 0.4566655737551359
204 Cost: 0.45663306536593185
205 Cost: 0.4566010786084647
206 Cost: 0.456569603832317
207 Cost: 0.4565386315939501
208 Cost: 0.4565081526516022
209 Cost: 0.4564781579603232
210 Cost: 0.45644863866716
211 Cost: 0.4564195861064673
212 Cost: 0.4563909917953483
213 Cost: 0.45636284742922695
214 Cost: 0.4563351448775378
215 Cost: 0.456307876179536
216 Cost: 0.45628103354022137
217 Cost: 0.4562546093263717
218 Cost: 0.4562285960626887
219 Cost: 0.45620298642804114
220 Cost: 0.4561777732518199
221 Cost: 0.45615294951037755
222 Cost: 0.4561285083235761
223 Cost: 0.4561044429514162
224 Cost: 0.45608074679076605
225 Cost: 0.45605741337216843
226 Cost: 0.4560344363567393
227 Cost: 0.45601180953314224
228 Cost: 0.455989526814644
229 Cost: 0.45596758223625344
230 Cost: 0.45594596995192255
231 Cost: 0.4559246842318344
232 Cost: 0.4559037194597474
233 Cost: 0.4558830701304241
234 Cost: 0.45586273084710827
235 Cost: 0.45584269631908303
236 Cost: 0.4558229613592805
237 Cost: 0.4558035208819584
238 Cost: 0.45578436990043086
239 Cost: 0.4557655035248646
240 Cost: 0.45574691696012165
241 Cost: 0.45572860550366157
242 Cost: 0.4557105645434978
243 Cost: 0.4556927895561975
244 Cost: 0.45567527610494246
245 Cost: 0.4556580198376304
246 Cost: 0.4556410164850232
247 Cost: 0.4556242618589468
248 Cost: 0.45560775185052954
249 Cost: 0.4555914824284865
250 Cost: 0.45557544963744445
251 Cost: 0.4555596495963138
252 Cost: 0.4555440784966874
253 Cost: 0.45552873260129395
254 Cost: 0.4555136082424735
255 Cost: 0.4554987018207051
256 Cost: 0.45548400980315407
257 Cost: 0.4554695287222681
258 Cost: 0.45545525517439756
259 Cost: 0.4554411858184566
260 Cost: 0.4554273173746045
261 Cost: 0.4554136466229713
262 Cost: 0.4554001704024051
263 Cost: 0.4553868856092533
264 Cost: 0.45537378919616883
265 Cost: 0.4553608781709471
266 Cost: 0.45534814959539033
267 Cost: 0.4553356005841943
268 Cost: 0.45532322830386845
269 Cost: 0.4553110299716731
270 Cost: 0.4552990028545862
271 Cost: 0.4552871442682901
272 Cost: 0.4552754515761898
273 Cost: 0.4552639221884409
274 Cost: 0.4552525535610121
275 Cost: 0.4552413431947591
276 Cost: 0.45523028863452913
277 Cost: 0.4552193874682765
278 Cost: 0.4552086373262053
279 Cost: 0.4551980358799269
280 Cost: 0.4551875808416376
281 Cost: 0.4551772699633188
282 Cost: 0.4551671010359479
283 Cost: 0.4551570718887301
284 Cost: 0.4551471803883507
285 Cost: 0.45513742443823746
286 Cost: 0.455127801977848
287 Cost: 0.4551183109819571
288 Cost: 0.4551089494599817
289 Cost: 0.45509971545530387
290 Cost: 0.4550906070446146
291 Cost: 0.455081622337268
292 Cost: 0.4550727594746584
293 Cost: 0.4550640166296032
294 Cost: 0.4550553920057391
295 Cost: 0.4550468838369351
296 Cost: 0.4550384903867168
297 Cost: 0.45503020994770355
298 Cost: 0.4550220408410557
299 Cost: 0.4550139814159352
300 Cost: 0.455006030048976
301 Cost: 0.4549981851437695
302 Cost: 0.4549904451303589
303 Cost: 0.4549828084647417
304 Cost: 0.45497527362838447
305 Cost: 0.45496783912775135
306 Cost: 0.4549605034938374
307 Cost: 0.4549532652817119
308 Cost: 0.4549461230700777
309 Cost: 0.45493907546083034
310 Cost: 0.4549321210786337
311 Cost: 0.45492525857050153
312 Cost: 0.45491848660538536
313 Cost: 0.45491180387377816
314 Cost: 0.454905209087316
315 Cost: 0.4548987009783977
316 Cost: 0.454892278299807
317 Cost: 0.45488593982434017
318 Cost: 0.45487968434444853
319 Cost: 0.4548735106718821
320 Cost: 0.45486741763734284
321 Cost: 0.4548614040901432
322 Cost: 0.454855468897876
323 Cost: 0.4548496109460842
324 Cost: 0.45484382913794424
325 Cost: 0.4548381223939498
326 Cost: 0.4548324896516065
327 Cost: 0.454826929865128
328 Cost: 0.45482144200514585
329 Cost: 0.4548160250584157
330 Cost: 0.4548106780275339
331 Cost: 0.454805399930662
332 Cost: 0.45480018980125286
333 Cost: 0.45479504668778215
334 Cost: 0.4547899696534905
335 Cost: 0.45478495777612354
336 Cost: 0.4547800101476772
337 Cost: 0.45477512587415914
338 Cost: 0.45477030407533836
339 Cost: 0.45476554388451645
340 Cost: 0.45476084444828296
341 Cost: 0.45475620492629937
342 Cost: 0.4547516244910672
343 Cost: 0.45474710232771215
344 Cost: 0.4547426376337672
345 Cost: 0.4547382296189617
346 Cost: 0.4547338775050154
347 Cost: 0.4547295805254325
348 Cost: 0.4547253379253038
349 Cost: 0.454721148961114
350 Cost: 0.4547170129005427
351 Cost: 0.45471292902228416
352 Cost: 0.45470889661585534
353 Cost: 0.454704914981421
354 Cost: 0.45470098342961046
355 Cost: 0.454697101281346
356 Cost: 0.4546932678676716
357 Cost: 0.45468948252958397
358 Cost: 0.4546857446178686
359 Cost: 0.454682053492934
360 Cost: 0.45467840852465974
361 Cost: 0.45467480909223346
362 Cost: 0.4546712545840027
363 Cost: 0.45466774439732344
364 Cost: 0.45466427793840875
365 Cost: 0.45466085462218997
366 Cost: 0.4546574738721702
367 Cost: 0.45465413512028713
368 Cost: 0.4546508378067739
369 Cost: 0.45464758138002814
370 Cost: 0.4546443652964719
371 Cost: 0.454641189020434
372 Cost: 0.4546380520240116
373 Cost: 0.45463495378695173
374 Cost: 0.4546318937965235
375 Cost: 0.4546288715474027
376 Cost: 0.45462588654155006
377 Cost: 0.4546229382880951
378 Cost: 0.4546200263032229
379 Cost: 0.4546171501100595
380 Cost: 0.45461430923856505
381 Cost: 0.4546115032254237
382 Cost: 0.4546087316139347
383 Cost: 0.45460599395391493
384 Cost: 0.4546032898015881
385 Cost: 0.45460061871948737
386 Cost: 0.45459798027635845
387 Cost: 0.45459537404705797
388 Cost: 0.4545927996124608
389 Cost: 0.45459025655936547
390 Cost: 0.4545877444803993
391 Cost: 0.45458526297393187
392 Cost: 0.4545828116439828
393 Cost: 0.4545803901001364
394 Cost: 0.4545779979574495
395 Cost: 0.4545756348363774
396 Cost: 0.4545733003626794
397 Cost: 0.45457099416734564
398 Cost: 0.45456871588651043
399 Cost: 0.4545664651613774
400 Cost: 0.45456424163814196
401 Cost: 0.45456204496790975
402 Cost: 0.45455987480663007
403 Cost: 0.4545577308150124
404 Cost: 0.45455561265846195
405 Cost: 0.45455352000700266
406 Cost: 0.45455145253521373
407 Cost: 0.45454940992215287
408 Cost: 0.45454739185129367
409 Cost: 0.45454539801045624
410 Cost: 0.454543428091745
411 Cost: 0.45454148179148196
412 Cost: 0.45453955881014235
413 Cost: 0.45453765885229436
414 Cost: 0.454535781626536
415 Cost: 0.4545339268454393
416 Cost: 0.45453209422548485
417 Cost: 0.4545302834870076
418 Cost: 0.4545284943541369
419 Cost: 0.4545267265547439
420 Cost: 0.45452497982038337
421 Cost: 0.45452325388623915
422 Cost: 0.4545215484910701
423 Cost: 0.4545198633771607
424 Cost: 0.45451819829026346
425 Cost: 0.4545165529795544
426 Cost: 0.45451492719757824
427 Cost: 0.4545133207001992
428 Cost: 0.45451173324655536
429 Cost: 0.45451016459900806
430 Cost: 0.45450861452309593
431 Cost: 0.454507082787487
432 Cost: 0.45450556916393764
433 Cost: 0.45450407342724236
434 Cost: 0.4545025953551918
435 Cost: 0.45450113472853054
436 Cost: 0.4544996913309137
437 Cost: 0.45449826494886386
438 Cost: 0.454496855371731
439 Cost: 0.4544954623916496
440 Cost: 0.45449408580350226
441 Cost: 0.45449272540487806
442 Cost: 0.4544913809960335
443 Cost: 0.4544900523798532
444 Cost: 0.4544887393618166
445 Cost: 0.45448744174995664
446 Cost: 0.45448615935482645
447 Cost: 0.4544848919894591
448 Cost: 0.4544836394693394
449 Cost: 0.4544824016123604
450 Cost: 0.45448117823879747
451 Cost: 0.45447996917126954
452 Cost: 0.45447877423470595
453 Cost: 0.4544775932563194
454 Cost: 0.4544764260655656
455 Cost: 0.4544752724941174
456 Cost: 0.45447413237583145
457 Cost: 0.4544730055467206
458 Cost: 0.45447189184491704
459 Cost: 0.4544707911106496
460 Cost: 0.4544697031862118
461 Cost: 0.4544686279159321
462 Cost: 0.454467565146145
463 Cost: 0.4544665147251688
464 Cost: 0.4544654765032679
465 Cost: 0.45446445033263544
466 Cost: 0.4544634360673627
467 Cost: 0.45446243356341104
468 Cost: 0.45446144267858885
469 Cost: 0.454460463272524
470 Cost: 0.45445949520664125
471 Cost: 0.4544585383441359
472 Cost: 0.45445759254994894
473 Cost: 0.4544566576907428
474 Cost: 0.4544557336348809
475 Cost: 0.45445482025239853
476 Cost: 0.4544539174149887
477 Cost: 0.45445302499596885
478 Cost: 0.454452142870268
479 Cost: 0.4544512709143988
480 Cost: 0.4544504090064391
481 Cost: 0.4544495570260087
482 Cost: 0.45444871485425076
483 Cost: 0.4544478823738087
484 Cost: 0.4544470594688066
485 Cost: 0.4544462460248299
486 Cost: 0.45444544192890574
487 Cost: 0.4544446470694828
488 Cost: 0.4544438613364098
489 Cost: 0.4544430846209226
490 Cost: 0.4544423168156218
491 Cost: 0.4544415578144519
492 Cost: 0.45444080751268845
493 Cost: 0.45444006580691676
494 Cost: 0.4544393325950159
495 Cost: 0.4544386077761405
496 Cost: 0.4544378912507051
497 Cost: 0.4544371829203652
498 Cost: 0.4544364826880024
499 Cost: 0.45443579045770743
[-0.86607655  1.28723986 -0.48826995 -0.32829487 -0.13482588  0.07371549
  0.15063765 -0.50443527]
[0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0]
223